---

- name: add nginx repository key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: add nginx repository
  apt_repository: repo='deb http://nginx.org/packages/mainline/debian/ jessie nginx' state=present

- name: add nginx src repository
  apt_repository: repo='deb-src http://nginx.org/packages/mainline/debian/ jessie nginx' state=present

- name: installing nginx
  apt: name=nginx state=latest

- name: Nginx Install | Make sure the nginx directory exists
  file:
    path: "{{nginx_dir}}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Nginx Install | Make sure the nginx log directory exists
  file:
    path: "{{nginx_log_dir}}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Nginx Install | Make sure the sites-available, sites-enabled and conf.d directories exist
  file:
    path: "{{nginx_dir}}/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items: ["sites-available", "sites-enabled", "conf.d"]

