# file: nginx/tasks/modules/http_realip_module.yml
# configure flag: --with-http_realip_module

- name: Nginx Configure | Modules | Update the http_realip_module configuration when enabled
  template:
    src: modules/http_realip.conf.j2
    dest: "{{nginx_dir}}/conf.d/http_realip.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx
  when: nginx_http_realip_module is defined and nginx_http_realip_module == true

- name: Nginx Configure | Modules | Remove the http_realip_module configuration when disabled
  file:
    path: "{{nginx_dir}}/conf.d/http_realip.conf"
    state: absent
  notify:
    - reload nginx
  when: nginx_http_realip_module is not defined or nginx_http_realip_module == false

